//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingsEnhanced.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SettingsEnhanced.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Notification_ConfigurationModified_Title {
            get {
                return ResourceManager.GetString("Notification_ConfigurationModified_Title", resourceCulture);
            }
        }
        
        internal static string Notification_ConfigurationModified_Content {
            get {
                return ResourceManager.GetString("Notification_ConfigurationModified_Content", resourceCulture);
            }
        }
        
        internal static string Notification_ConfigurationRestored_Title {
            get {
                return ResourceManager.GetString("Notification_ConfigurationRestored_Title", resourceCulture);
            }
        }
        
        internal static string Notification_ConfigurationRestored_Content {
            get {
                return ResourceManager.GetString("Notification_ConfigurationRestored_Content", resourceCulture);
            }
        }
        
        internal static string UI_Titlebar_SupportDeveloper {
            get {
                return ResourceManager.GetString("UI_Titlebar_SupportDeveloper", resourceCulture);
            }
        }
        
        internal static string UI_Titlebar_Repository {
            get {
                return ResourceManager.GetString("UI_Titlebar_Repository", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningTitle {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningTitle", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningText1 {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningText1", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningText2 {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningText2", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningText3 {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningText3", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningText4 {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningText4", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningText5 {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningText5", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningBackupRequired {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningBackupRequired", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningContinueButton {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningContinueButton", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_WarningContinueHint {
            get {
                return ResourceManager.GetString("UI_Configuration_WarningContinueHint", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_SettingsType_Zone_Title {
            get {
                return ResourceManager.GetString("UI_Configuration_SettingsType_Zone_Title", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_SettingsType_Zone_Description {
            get {
                return ResourceManager.GetString("UI_Configuration_SettingsType_Zone_Description", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_SettingsType_Game_Title {
            get {
                return ResourceManager.GetString("UI_Configuration_SettingsType_Game_Title", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_SettingsType_Game_Description {
            get {
                return ResourceManager.GetString("UI_Configuration_SettingsType_Game_Description", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_Zonelist_CustomSettings {
            get {
                return ResourceManager.GetString("UI_Configuration_Zonelist_CustomSettings", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_Zonelist_DefaultSettings {
            get {
                return ResourceManager.GetString("UI_Configuration_Zonelist_DefaultSettings", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_ZoneConfig_SystemConfig {
            get {
                return ResourceManager.GetString("UI_Configuration_ZoneConfig_SystemConfig", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_ZoneConfig_CharaConfig {
            get {
                return ResourceManager.GetString("UI_Configuration_ZoneConfig_CharaConfig", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_ZoneConfig_ApplyButton {
            get {
                return ResourceManager.GetString("UI_Configuration_ZoneConfig_ApplyButton", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_ZoneConfig_DeleteButton {
            get {
                return ResourceManager.GetString("UI_Configuration_ZoneConfig_DeleteButton", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_ZoneConfig_DeleteButton_Hint {
            get {
                return ResourceManager.GetString("UI_Configuration_ZoneConfig_DeleteButton_Hint", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_ZoneConfig_ResetToDefault {
            get {
                return ResourceManager.GetString("UI_Configuration_ZoneConfig_ResetToDefault", resourceCulture);
            }
        }
        
        internal static string UI_Configuration_ZoneConfig_EnumFallback {
            get {
                return ResourceManager.GetString("UI_Configuration_ZoneConfig_EnumFallback", resourceCulture);
            }
        }
    }
}
